output_root: '/home/haitian003/__workbase__/UMSS/self_cons2/SCON'
pytorch_data_dir: '/home/haitian003/__dataset__/UMSS/COCOSTUFF'
log_dir: "cocostuff27"
azureml_logging: False
submitting_to_aml: False
entity: "haitian003-nanyang-technological-university-singapore"
num_workers: 24
max_steps: 60000
num_neighbors: 7
dataset_name: "cocostuff27"
dir_dataset_name: ~
dir_dataset_n_classes: 5
has_labels: False
crop_type: "five"
crop_ratio: .5
res: 224
loader_crop_type: "center"
# Model Params
extra_clusters: 0
use_true_labels: False
use_recalibrator: False

##############################
project_name: "RecSeg" 
batch_size: 32
gpu_ids: "2"
experiment_name: "v3S_16_ssim"
model_type: "vit_small"
dino_version: "v3"
dino_patch_size: 16
dino_feat_type: "ori" # 'ori' or 'fea'
##############################

pos_inter_weight: 0.3951
pos_intra_weight: 0.4738
neg_inter_weight: 0.6312
neg_inter_shift: 0.3821
pos_inter_shift: 0.4398
pos_intra_shift: 0.7596
recon_hidden_dim: 256
soft_cluster_alpha: 2.0500
stego_loss_weight: 0.5264
recon_loss_weight: 0.2476
recon_lr: 0.0022
soft_cluster_lr: 0.0039
dim: 128

# ===== SCON2新增：重建loss相关参数 =====
recon_type: "shallow" # 'shallow' or 'deep'
recon_loss_type: 'ssim' #['mse', 'cosine', 'relaxed_cosine', 'ssim']


pretrained_weights: "../Pretrained_Models/dinov3_vits16_pretrain_lvd1689m-08c60483.pth"
# pretrained_weights: "../Pretrained_Models/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth"
# pretrained_seg: "/home/haitian003/__workbase__/UMSS/self_cons2/Pretrained_Models/for_recons/vit-base-31.79.ckpt"
pretrained_seg: "/home/haitian003/__workbase__/UMSS/self_cons2/Pretrained_Models/for_recons/vit-small-29.12.ckpt"

##############################
search_dim: False
###############################

arch: "dino"
use_fit_model: False
projection_type: "nonlinear"
granularity: 1
continuous: True
dropout: True
zero_clamp: True
lr: 5e-4

use_salience: False
stabalize: False
stop_at_zero: True

# Feature Contrastive params
pointwise: True
feature_samples: 11
neg_samples: 5
aug_alignment_weight: 0.0
correspondence_weight: 1.0
rec_weight: 0.0
repulsion_weight: 0.0

# CRF Params
crf_weight: 0.0
alpha: .5
beta: .15
gamma: .05
w1: 10.0
w2: 3.0
shift: 0.00
crf_samples: 1000
color_space: "rgb"
reset_probe_steps: ~

# Logging params
n_images: 5
scalar_log_freq: 10
checkpoint_freq: 50
val_freq: 25
hist_freq: 100

hydra:
  run:
    dir: ${output_root}
  output_subdir: null
  job_logging:
    handlers:
      file:
        filename: ${output_root}/logs/${hydra.job.name}.log

